/**
 * Slim SegDB → SNOMED lookup for DICOM SR reporting (and IRA catalog fill).
 * Source: products/mhub/MHubSkill/data/segdb_cache.json
 * (cache_date: 2025-01-29).
 * Generated by:
 *   node cast_resource_servers/products/mhub/export_ira_catalog.mjs
 */

export type SegdbEntry = {
  name: string;
  categoryCode: string;
  categoryScheme: string;
  categoryMeaning: string;
  typeCode: string;
  typeScheme: string;
  typeMeaning: string;
  modifier: string;
};

export type SegdbCoded = {
  scheme: string;
  value: string;
  meaning: string;
};

export type SegdbTerminology = {
  category: SegdbCoded | null;
  type: SegdbCoded | null;
  typeModifier: SegdbCoded | null;
  region: SegdbCoded | null;
};

/** @type {Readonly<Record<string, SegdbEntry>>} */
export const SEGDB_BY_ID: Readonly<Record<string, SegdbEntry>> = Object.freeze(
  {
  "LEFT_ADRENAL_GLAND": {
    "name": "Left adrenal gland",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "23451007",
    "typeScheme": "SCT",
    "typeMeaning": "Adrenal structure",
    "modifier": "M_LEFT"
  },
  "RIGHT_ADRENAL_GLAND": {
    "name": "Right adrenal gland",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "23451007",
    "typeScheme": "SCT",
    "typeMeaning": "Adrenal structure",
    "modifier": "M_RIGHT"
  },
  "AORTA": {
    "name": "Aorta",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "15825003",
    "typeScheme": "SCT",
    "typeMeaning": "Aortic structure",
    "modifier": ""
  },
  "LEFT_AUTOCHTHONOUS_BACK_MUSCLE": {
    "name": "Left autochthonous back muscle",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "244849004",
    "typeScheme": "SCT",
    "typeMeaning": "Autochthonous back muscle structure",
    "modifier": "M_LEFT"
  },
  "RIGHT_AUTOCHTHONOUS_BACK_MUSCLE": {
    "name": "Right autochthonous back muscle",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "244849004",
    "typeScheme": "SCT",
    "typeMeaning": "Autochthonous back muscle structure",
    "modifier": "M_RIGHT"
  },
  "BRAIN": {
    "name": "Brain",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "12738006",
    "typeScheme": "SCT",
    "typeMeaning": "Brain structure",
    "modifier": ""
  },
  "LEFT_CLAVICLE": {
    "name": "Left clavicle",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "51299004",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of clavicle",
    "modifier": "M_LEFT"
  },
  "RIGHT_CLAVICLE": {
    "name": "Right clavicle",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "51299004",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of clavicle",
    "modifier": "M_RIGHT"
  },
  "COLON": {
    "name": "Colon",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "71854001",
    "typeScheme": "SCT",
    "typeMeaning": "Colon structure",
    "modifier": ""
  },
  "DUODENUM": {
    "name": "Duodenum",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "38848004",
    "typeScheme": "SCT",
    "typeMeaning": "Duodenal structure",
    "modifier": ""
  },
  "ESOPHAGUS": {
    "name": "Esophagus",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "32849002",
    "typeScheme": "SCT",
    "typeMeaning": "Esophageal structure",
    "modifier": ""
  },
  "FACE": {
    "name": "Face",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "89545001",
    "typeScheme": "SCT",
    "typeMeaning": "Face structure",
    "modifier": ""
  },
  "LEFT_FEMUR": {
    "name": "Left femur",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "71341001",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of femur",
    "modifier": "M_LEFT"
  },
  "RIGHT_FEMUR": {
    "name": "Right femur",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "71341001",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of femur",
    "modifier": "M_RIGHT"
  },
  "GALLBLADDER": {
    "name": "Gallbladder",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "28231008",
    "typeScheme": "SCT",
    "typeMeaning": "Gallbladder structure",
    "modifier": ""
  },
  "LEFT_GLUTEUS_MAXIMUS": {
    "name": "Left gluteus maximus",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "181674001",
    "typeScheme": "SCT",
    "typeMeaning": "Muscle structure of the gluteus maximus",
    "modifier": "M_LEFT"
  },
  "RIGHT_GLUTEUS_MAXIMUS": {
    "name": "Right gluteus maximus",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "181674001",
    "typeScheme": "SCT",
    "typeMeaning": "Muscle structure of the gluteus maximus",
    "modifier": "M_RIGHT"
  },
  "LEFT_GLUTEUS_MEDIUS": {
    "name": "Left gluteus medius",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "78333006",
    "typeScheme": "SCT",
    "typeMeaning": "Muscle structure of the gluteus medius",
    "modifier": "M_LEFT"
  },
  "RIGHT_GLUTEUS_MEDIUS": {
    "name": "Right gluteus medius",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "78333006",
    "typeScheme": "SCT",
    "typeMeaning": "Muscle structure of the gluteus medius",
    "modifier": "M_RIGHT"
  },
  "LEFT_GLUTEUS_MINIMUS": {
    "name": "Left gluteus minimus",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "75297007",
    "typeScheme": "SCT",
    "typeMeaning": "Muscle structure of the gluteus minumus",
    "modifier": "M_LEFT"
  },
  "RIGHT_GLUTEUS_MINIMUS": {
    "name": "Right gluteus minimus",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "75297007",
    "typeScheme": "SCT",
    "typeMeaning": "Muscle structure of the gluteus minumus",
    "modifier": "M_RIGHT"
  },
  "LEFT_ATRIUM": {
    "name": "Left atrium",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "59652004",
    "typeScheme": "SCT",
    "typeMeaning": "Atrial structure",
    "modifier": "M_LEFT"
  },
  "RIGHT_ATRIUM": {
    "name": "Right atrium",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "59652004",
    "typeScheme": "SCT",
    "typeMeaning": "Atrial structure",
    "modifier": "M_RIGHT"
  },
  "MYOCARDIUM": {
    "name": "Myocardium",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "74281007",
    "typeScheme": "SCT",
    "typeMeaning": "Muscle structure of the myocardium",
    "modifier": ""
  },
  "LEFT_VENTRICLE": {
    "name": "Left ventricle",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "87878005",
    "typeScheme": "SCT",
    "typeMeaning": "Left cardiac ventricular structure",
    "modifier": ""
  },
  "RIGHT_VENTRICLE": {
    "name": "Right ventricle",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "53085002",
    "typeScheme": "SCT",
    "typeMeaning": "Right cardiac ventricular structure",
    "modifier": ""
  },
  "LEFT_HIP": {
    "name": "Left hip",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "29836001",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of the hip",
    "modifier": ""
  },
  "RIGHT_HIP": {
    "name": "Right hip",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "29836001",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of the hip",
    "modifier": ""
  },
  "LEFT_HUMERUS": {
    "name": "Left humerus",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "85050009",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of humerus",
    "modifier": "M_LEFT"
  },
  "RIGHT_HUMERUS": {
    "name": "Right humerus",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "85050009",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of humerus",
    "modifier": "M_RIGHT"
  },
  "LEFT_ILIAC_ARTERY": {
    "name": "Left iliac artery",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "73634005",
    "typeScheme": "SCT",
    "typeMeaning": "Common iliac artery structure",
    "modifier": "M_LEFT"
  },
  "RIGHT_ILIAC_ARTERY": {
    "name": "Right iliac artery",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "73634005",
    "typeScheme": "SCT",
    "typeMeaning": "Common iliac artery structure",
    "modifier": "M_RIGHT"
  },
  "LEFT_ILIAC_VEIN": {
    "name": "Left iliac vein",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "46027005",
    "typeScheme": "SCT",
    "typeMeaning": "Structure of common iliac vein",
    "modifier": "M_LEFT"
  },
  "RIGHT_ILIAC_VEIN": {
    "name": "Right iliac vein",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "46027005",
    "typeScheme": "SCT",
    "typeMeaning": "Structure of common iliac vein",
    "modifier": "M_RIGHT"
  },
  "LEFT_ILIOPSOAS": {
    "name": "Left iliopsoas",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "68455001",
    "typeScheme": "SCT",
    "typeMeaning": "Muscle structure of the iliopsoas",
    "modifier": "M_LEFT"
  },
  "RIGHT_ILIOPSOAS": {
    "name": "Right iliopsoas",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "68455001",
    "typeScheme": "SCT",
    "typeMeaning": "Muscle structure of the iliopsoas",
    "modifier": "M_RIGHT"
  },
  "INFERIOR_VENA_CAVA": {
    "name": "Inferior vena cava",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "64131007",
    "typeScheme": "SCT",
    "typeMeaning": "Inferior vena cava structure",
    "modifier": ""
  },
  "SUPERIOR_VENA_CAVA": {
    "name": "Superior vena cava",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "48345005",
    "typeScheme": "SCT",
    "typeMeaning": "Superior vena cava structure",
    "modifier": ""
  },
  "LEFT_KIDNEY": {
    "name": "Left kidney",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "64033007",
    "typeScheme": "SCT",
    "typeMeaning": "Kidney structure",
    "modifier": "M_LEFT"
  },
  "RIGHT_KIDNEY": {
    "name": "Right kidney",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "64033007",
    "typeScheme": "SCT",
    "typeMeaning": "Kidney structure",
    "modifier": "M_RIGHT"
  },
  "KIDNEY": {
    "name": "Kidney",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "64033007",
    "typeScheme": "SCT",
    "typeMeaning": "Kidney structure",
    "modifier": ""
  },
  "LIVER": {
    "name": "Liver",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "10200004",
    "typeScheme": "SCT",
    "typeMeaning": "Liver structure",
    "modifier": ""
  },
  "LEFT_LUNG": {
    "name": "Left lung",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "39607008",
    "typeScheme": "SCT",
    "typeMeaning": "Structure of lung",
    "modifier": "M_LEFT"
  },
  "RIGHT_LUNG": {
    "name": "Right lung",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "39607008",
    "typeScheme": "SCT",
    "typeMeaning": "Structure of lung",
    "modifier": "M_RIGHT"
  },
  "LEFT_LOWER_LUNG_LOBE": {
    "name": "Left lower lung lobe",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "90572001",
    "typeScheme": "SCT",
    "typeMeaning": "Structure of lower lobe of lung",
    "modifier": "M_LEFT"
  },
  "RIGHT_LOWER_LUNG_LOBE": {
    "name": "Right lower lung lobe",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "90572001",
    "typeScheme": "SCT",
    "typeMeaning": "Structure of lower lobe of lung",
    "modifier": "M_RIGHT"
  },
  "RIGHT_MIDDLE_LUNG_LOBE": {
    "name": "Right middle lung lobe",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "72481006",
    "typeScheme": "SCT",
    "typeMeaning": "Structure of middle lobe of right lung",
    "modifier": ""
  },
  "LEFT_UPPER_LUNG_LOBE": {
    "name": "Left upper lung lobe",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "45653009",
    "typeScheme": "SCT",
    "typeMeaning": "Structure of upper lobe of lung",
    "modifier": "M_LEFT"
  },
  "RIGHT_UPPER_LUNG_LOBE": {
    "name": "Right upper lung lobe",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "45653009",
    "typeScheme": "SCT",
    "typeMeaning": "Structure of upper lobe of lung",
    "modifier": "M_RIGHT"
  },
  "PANCREAS": {
    "name": "Pancreas",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "15776009",
    "typeScheme": "SCT",
    "typeMeaning": "Pancreatic structure",
    "modifier": ""
  },
  "PORTAL_AND_SPLENIC_VEIN": {
    "name": "Portal and splenic vein",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "29092000",
    "typeScheme": "SCT",
    "typeMeaning": "Venous structure",
    "modifier": ""
  },
  "PULMONARY_ARTERY": {
    "name": "Pulmonary artery",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "81040000",
    "typeScheme": "SCT",
    "typeMeaning": "Pulmonary artery structure",
    "modifier": ""
  },
  "LEFT_RIB_10": {
    "name": "Left rib 10",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "77644006",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of tenth rib",
    "modifier": "M_LEFT"
  },
  "LEFT_RIB_11": {
    "name": "Left rib 11",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "58830002",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of eleventh rib",
    "modifier": "M_LEFT"
  },
  "LEFT_RIB_12": {
    "name": "Left rib 12",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "43993008",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of twelfth rib",
    "modifier": "M_LEFT"
  },
  "LEFT_RIB_1": {
    "name": "Left rib 1",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "48535007",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of first rib",
    "modifier": "M_LEFT"
  },
  "LEFT_RIB_2": {
    "name": "Left rib 2",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "78247007",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of second rib",
    "modifier": "M_LEFT"
  },
  "LEFT_RIB_3": {
    "name": "Left rib 3",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "25888004",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of third rib",
    "modifier": "M_LEFT"
  },
  "LEFT_RIB_4": {
    "name": "Left rib 4",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "25523003",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of fourth rib",
    "modifier": "M_LEFT"
  },
  "LEFT_RIB_5": {
    "name": "Left rib 5",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "15339008",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of fifth rib",
    "modifier": "M_LEFT"
  },
  "LEFT_RIB_6": {
    "name": "Left rib 6",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "59558009",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of sixth rib",
    "modifier": "M_LEFT"
  },
  "LEFT_RIB_7": {
    "name": "Left rib 7",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "24915002",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of seventh rib",
    "modifier": "M_LEFT"
  },
  "LEFT_RIB_8": {
    "name": "Left rib 8",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "5953002",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of eight rib",
    "modifier": "M_LEFT"
  },
  "LEFT_RIB_9": {
    "name": "Left rib 9",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "22565002",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of ninth rib",
    "modifier": "M_LEFT"
  },
  "RIGHT_RIB_10": {
    "name": "Right rib 10",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "77644006",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of tenth rib",
    "modifier": "M_RIGHT"
  },
  "RIGHT_RIB_11": {
    "name": "Right rib 11",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "58830002",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of eleventh rib",
    "modifier": "M_RIGHT"
  },
  "RIGHT_RIB_12": {
    "name": "Right rib 12",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "43993008",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of twelfth rib",
    "modifier": "M_RIGHT"
  },
  "RIGHT_RIB_1": {
    "name": "Right rib 1",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "48535007",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of first rib",
    "modifier": "M_RIGHT"
  },
  "RIGHT_RIB_2": {
    "name": "Right rib 2",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "78247007",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of second rib",
    "modifier": "M_RIGHT"
  },
  "RIGHT_RIB_3": {
    "name": "Right rib 3",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "25888004",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of third rib",
    "modifier": "M_RIGHT"
  },
  "RIGHT_RIB_4": {
    "name": "Right rib 4",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "25523003",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of fourth rib",
    "modifier": "M_RIGHT"
  },
  "RIGHT_RIB_5": {
    "name": "Right rib 5",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "15339008",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of fifth rib",
    "modifier": "M_RIGHT"
  },
  "RIGHT_RIB_6": {
    "name": "Right rib 6",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "59558009",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of sixth rib",
    "modifier": "M_RIGHT"
  },
  "RIGHT_RIB_7": {
    "name": "Right rib 7",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "24915002",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of seventh rib",
    "modifier": "M_RIGHT"
  },
  "RIGHT_RIB_8": {
    "name": "Right rib 8",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "5953002",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of eight rib",
    "modifier": "M_RIGHT"
  },
  "RIGHT_RIB_9": {
    "name": "Right rib 9",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "22565002",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of ninth rib",
    "modifier": "M_RIGHT"
  },
  "SACRUM": {
    "name": "Sacrum",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "54735007",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of sacrum",
    "modifier": ""
  },
  "LEFT_SCAPULA": {
    "name": "Left scapula",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "79601000",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of scapula",
    "modifier": "M_LEFT"
  },
  "RIGHT_SCAPULA": {
    "name": "Right scapula",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "79601000",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of scapula",
    "modifier": "M_RIGHT"
  },
  "SMALL_INTESTINE": {
    "name": "Small intestine",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "30315005",
    "typeScheme": "SCT",
    "typeMeaning": "Structure of small intestine",
    "modifier": ""
  },
  "SPLEEN": {
    "name": "Spleen",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "78961009",
    "typeScheme": "SCT",
    "typeMeaning": "Splenic structure",
    "modifier": ""
  },
  "STOMACH": {
    "name": "Stomach",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "69695003",
    "typeScheme": "SCT",
    "typeMeaning": "Stomach structure",
    "modifier": ""
  },
  "TRACHEA": {
    "name": "Trachea",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "44567001",
    "typeScheme": "SCT",
    "typeMeaning": "Tracheal structure",
    "modifier": ""
  },
  "URINARY_BLADDER": {
    "name": "Urinary bladder",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "89837001",
    "typeScheme": "SCT",
    "typeMeaning": "Urinary bladder structure",
    "modifier": ""
  },
  "VERTEBRAE_C1": {
    "name": "Vertebrae C1",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "14806007",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of vertebrae C1",
    "modifier": ""
  },
  "VERTEBRAE_C2": {
    "name": "Vertebrae C2",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "39976000",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of vertebrae C2",
    "modifier": ""
  },
  "VERTEBRAE_C3": {
    "name": "Vertebrae C3",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "113205007",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of vertebrae C3",
    "modifier": ""
  },
  "VERTEBRAE_C4": {
    "name": "Vertebrae C4",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "5329002",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of vertebrae C4",
    "modifier": ""
  },
  "VERTEBRAE_C5": {
    "name": "Vertebrae C5",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "36978003",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of vertebrae C5",
    "modifier": ""
  },
  "VERTEBRAE_C6": {
    "name": "Vertebrae C6",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "36054005",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of vertebrae C6",
    "modifier": ""
  },
  "VERTEBRAE_C7": {
    "name": "Vertebrae C7",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "87391001",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of vertebrae C7",
    "modifier": ""
  },
  "VERTEBRAE_L1": {
    "name": "Vertebrae L1",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "66794005",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of vertebrae L1",
    "modifier": ""
  },
  "VERTEBRAE_L2": {
    "name": "Vertebrae L2",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "14293000",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of vertebrae L2",
    "modifier": ""
  },
  "VERTEBRAE_L3": {
    "name": "Vertebrae L3",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "36470004",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of vertebrae L3",
    "modifier": ""
  },
  "VERTEBRAE_L4": {
    "name": "Vertebrae L4",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "11994002",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of vertebrae L4",
    "modifier": ""
  },
  "VERTEBRAE_L5": {
    "name": "Vertebrae L5",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "49668003",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of vertebrae L5",
    "modifier": ""
  },
  "VERTEBRAE_T10": {
    "name": "Vertebrae T10",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "7610001",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of vertebrae T10",
    "modifier": ""
  },
  "VERTEBRAE_T11": {
    "name": "Vertebrae T11",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "12989004",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of vertebrae T11",
    "modifier": ""
  },
  "VERTEBRAE_T12": {
    "name": "Vertebrae T12",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "23215003",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of vertebrae T12",
    "modifier": ""
  },
  "VERTEBRAE_T1": {
    "name": "Vertebrae T1",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "64864005",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of vertebrae T1",
    "modifier": ""
  },
  "VERTEBRAE_T2": {
    "name": "Vertebrae T2",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "53733008",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of vertebrae T2",
    "modifier": ""
  },
  "VERTEBRAE_T3": {
    "name": "Vertebrae T3",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "1626008",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of vertebrae T3",
    "modifier": ""
  },
  "VERTEBRAE_T4": {
    "name": "Vertebrae T4",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "73071006",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of vertebrae T4",
    "modifier": ""
  },
  "VERTEBRAE_T5": {
    "name": "Vertebrae T5",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "56401006",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of vertebrae T5",
    "modifier": ""
  },
  "VERTEBRAE_T6": {
    "name": "Vertebrae T6",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "45296009",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of vertebrae T6",
    "modifier": ""
  },
  "VERTEBRAE_T7": {
    "name": "Vertebrae T7",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "62487009",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of vertebrae T7",
    "modifier": ""
  },
  "VERTEBRAE_T8": {
    "name": "Vertebrae T8",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "11068009",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of vertebrae T8",
    "modifier": ""
  },
  "VERTEBRAE_T9": {
    "name": "Vertebrae T9",
    "categoryCode": "85756007",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body tissue structure",
    "typeCode": "82687006",
    "typeScheme": "SCT",
    "typeMeaning": "Bone structure of vertebrae T9",
    "modifier": ""
  },
  "VERTEBRAE_DISK_C2C3": {
    "name": "Vertebrae Disk C2/C3",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "1078209008",
    "typeScheme": "SCT",
    "typeMeaning": "Intervertebral disc structure of second cervical vertebra (body structure)",
    "modifier": ""
  },
  "VERTEBRAE_DISK_C3C4": {
    "name": "Vertebrae Disk C3/C4",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "58820006",
    "typeScheme": "SCT",
    "typeMeaning": "Intervertebral disc structure of third cervical vertebra (body structure)",
    "modifier": ""
  },
  "VERTEBRAE_DISK_C4C5": {
    "name": "Vertebrae Disk C4/C5",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "49400002",
    "typeScheme": "SCT",
    "typeMeaning": "Intervertebral disc structure of fourth cervical vertebra (body structure)",
    "modifier": ""
  },
  "VERTEBRAE_DISK_C5C6": {
    "name": "Vertebrae Disk C5/C6",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "73959003",
    "typeScheme": "SCT",
    "typeMeaning": "Intervertebral disc structure of fifth cervical vertebra (body structure)",
    "modifier": ""
  },
  "VERTEBRAE_DISK_C6C7": {
    "name": "Vertebrae Disk C6/C7",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "75095006",
    "typeScheme": "SCT",
    "typeMeaning": "Intervertebral disc structure of sixth cervical vertebra (body structure)",
    "modifier": ""
  },
  "VERTEBRAE_DISK_C7T1": {
    "name": "Vertebrae Disk C7/T1",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "37414007",
    "typeScheme": "SCT",
    "typeMeaning": "Intervertebral disc structure of seventh cervical vertebra (body structure)",
    "modifier": ""
  },
  "VERTEBRAE_DISK_T1T2": {
    "name": "Vertebrae Disk T1/T2",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "40908007",
    "typeScheme": "SCT",
    "typeMeaning": "Intervertebral disc structure of first thoracic vertebra (body structure)",
    "modifier": ""
  },
  "VERTEBRAE_DISK_T2T3": {
    "name": "Vertebrae Disk T2/T3",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "6004007",
    "typeScheme": "SCT",
    "typeMeaning": "Intervertebral disc structure of second thoracic vertebra (body structure)",
    "modifier": ""
  },
  "VERTEBRAE_DISK_T3T4": {
    "name": "Vertebrae Disk T3/T4",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "2620004",
    "typeScheme": "SCT",
    "typeMeaning": "Intervertebral disc structure of third thoracic vertebra (body structure)",
    "modifier": ""
  },
  "VERTEBRAE_DISK_T4T5": {
    "name": "Vertebrae Disk T4/T5",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "82965004",
    "typeScheme": "SCT",
    "typeMeaning": "Intervertebral disc structure of fourth thoracic vertebra (body structure)",
    "modifier": ""
  },
  "VERTEBRAE_DISK_T5T6": {
    "name": "Vertebrae Disk T5/T6",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "72692000",
    "typeScheme": "SCT",
    "typeMeaning": "Intervertebral disc structure of fifth thoracic vertebra (body structure)",
    "modifier": ""
  },
  "VERTEBRAE_DISK_T6T7": {
    "name": "Vertebrae Disk T6/T7",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "74401007",
    "typeScheme": "SCT",
    "typeMeaning": "Intervertebral disc structure of sixth thoracic vertebra (body structure)",
    "modifier": ""
  },
  "VERTEBRAE_DISK_T7T8": {
    "name": "Vertebrae Disk T7/T8",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "28693002",
    "typeScheme": "SCT",
    "typeMeaning": "Intervertebral disc structure of seventh thoracic vertebra (body structure)",
    "modifier": ""
  },
  "VERTEBRAE_DISK_T8T9": {
    "name": "Vertebrae Disk T8/T9",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "9188009",
    "typeScheme": "SCT",
    "typeMeaning": "Intervertebral disc structure of eighth thoracic vertebra (body structure)",
    "modifier": ""
  },
  "VERTEBRAE_DISK_T9T10": {
    "name": "Vertebrae Disk T9/T10",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "113209001",
    "typeScheme": "SCT",
    "typeMeaning": "Intervertebral disc structure of ninth thoracic vertebra (body structure)",
    "modifier": ""
  },
  "VERTEBRAE_DISK_T10T11": {
    "name": "Vertebrae Disk T10/T11",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "34959001",
    "typeScheme": "SCT",
    "typeMeaning": "Intervertebral disc structure of tenth thoracic vertebra (body structure)",
    "modifier": ""
  },
  "VERTEBRAE_DISK_T11T12": {
    "name": "Vertebrae Disk T11/T12",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "1537001",
    "typeScheme": "SCT",
    "typeMeaning": "Intervertebral disc structure of eleventh thoracic vertebra (body structure)",
    "modifier": ""
  },
  "VERTEBRAE_DISK_T12L1": {
    "name": "Vertebrae Disk T12/L1",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "76206002",
    "typeScheme": "SCT",
    "typeMeaning": "Intervertebral disc structure of twelfth thoracic vertebra (body structure)",
    "modifier": ""
  },
  "VERTEBRAE_DISK_L1L2": {
    "name": "Vertebrae Disk L1/L2",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "80064006",
    "typeScheme": "SCT",
    "typeMeaning": "Intervertebral disc structure of first lumbar vertebra (body structure)",
    "modifier": ""
  },
  "VERTEBRAE_DISK_L2L3": {
    "name": "Vertebrae Disk L2/L3",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "67459009",
    "typeScheme": "SCT",
    "typeMeaning": "Intervertebral disc structure of second lumbar vertebra (body structure)",
    "modifier": ""
  },
  "VERTEBRAE_DISK_L3L4": {
    "name": "Vertebrae Disk L3/L4",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "62551000",
    "typeScheme": "SCT",
    "typeMeaning": "Intervertebral disc structure of third lumbar vertebra (body structure)",
    "modifier": ""
  },
  "VERTEBRAE_DISK_L4L5": {
    "name": "Vertebrae Disk L4/L5",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "84020006",
    "typeScheme": "SCT",
    "typeMeaning": "Intervertebral disc structure of fourth lumbar vertebra (body structure)",
    "modifier": ""
  },
  "VERTEBRAE_DISK_L5S1": {
    "name": "Vertebrae Disk L5/S1",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "715056000",
    "typeScheme": "SCT",
    "typeMeaning": "Structure of intervertebral disc of L5 and S1 (body structure)",
    "modifier": ""
  },
  "CORONARY_ARTERY_RIGHT": {
    "name": "Right Coronary Artery",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "13647002",
    "typeScheme": "SCT",
    "typeMeaning": "Right coronary artery structure",
    "modifier": ""
  },
  "CORONARY_ARTERY_LEFT": {
    "name": "Left Coronary Artery",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "3227004",
    "typeScheme": "SCT",
    "typeMeaning": "Structure of left main coronary artery",
    "modifier": ""
  },
  "CORONARY_ARTERY_CFLX": {
    "name": "Circumflex Branch of the Coronary Artery",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "57396003",
    "typeScheme": "SCT",
    "typeMeaning": "Structure of circumflex branch of left coronary artery",
    "modifier": ""
  },
  "CORONARY_ARTERY_LAD": {
    "name": "Left Anterior Descending Coronary Artery",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "59438005",
    "typeScheme": "SCT",
    "typeMeaning": "Structure of left anterior descending artery",
    "modifier": ""
  },
  "CORONARY_ARTERY": {
    "name": "Coronary Artery",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "41801008",
    "typeScheme": "SCT",
    "typeMeaning": "Coronary artery structure (body structure)",
    "modifier": ""
  },
  "HEART": {
    "name": "Heart",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "80891009",
    "typeScheme": "SCT",
    "typeMeaning": "Heart structure",
    "modifier": ""
  },
  "NEOPLASM_MALIGNANT_PRIMARY": {
    "name": "Primary malignant neoplasm",
    "categoryCode": "49755003",
    "categoryScheme": "SCT",
    "categoryMeaning": "Morphologically abnormal structure",
    "typeCode": "86049000",
    "typeScheme": "SCT",
    "typeMeaning": "Malignant neoplasm, primary (morphologic abnormality)",
    "modifier": ""
  },
  "AORTIC_VALVE": {
    "name": "Aortic valve",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "34202007",
    "typeScheme": "SCT",
    "typeMeaning": "Aortic valve structure",
    "modifier": ""
  },
  "MITRAL_VALVE": {
    "name": "Mitral valve",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "91134007",
    "typeScheme": "SCT",
    "typeMeaning": "Mitral valve structure",
    "modifier": ""
  },
  "PULMONARY_VALVE": {
    "name": "Pulmonary valve",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "39057004",
    "typeScheme": "SCT",
    "typeMeaning": "Pulmonary valve structure",
    "modifier": ""
  },
  "TRICUSPID_VALVE": {
    "name": "Tricuspid valve",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "46030003",
    "typeScheme": "SCT",
    "typeMeaning": "Tricuspid valve structure",
    "modifier": ""
  },
  "SINOTRIAL_NODE": {
    "name": "Sinoatrial conduction node",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "88210001",
    "typeScheme": "SCT",
    "typeMeaning": "Structure of sinoatrial node",
    "modifier": ""
  },
  "ATRIOVENTRICULAR_NODE": {
    "name": "Atrioventricular conduction node",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "25943004",
    "typeScheme": "SCT",
    "typeMeaning": "Structure of atrioventricular node",
    "modifier": ""
  },
  "PROSTATE": {
    "name": "Prostate",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "41216001",
    "typeScheme": "SCT",
    "typeMeaning": "Prostatic structure",
    "modifier": ""
  },
  "PROSTATE_PERIPHERAL_ZONE": {
    "name": "Peripheral zone of prostate",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "279706003",
    "typeScheme": "SCT",
    "typeMeaning": "Structure of peripheral glandular zone of prostate (body structure)",
    "modifier": ""
  },
  "PROSTATE_TRANSITION_ZONE": {
    "name": "Transition zone of prostate",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "399384005",
    "typeScheme": "SCT",
    "typeMeaning": "Structure of transition zone of prostate (body structure)",
    "modifier": ""
  },
  "CYST": {
    "name": "Cyst",
    "categoryCode": "49755003",
    "categoryScheme": "SCT",
    "categoryMeaning": "Morphologically abnormal structure",
    "typeCode": "367643001",
    "typeScheme": "SCT",
    "typeMeaning": "Cyst (morphologic abnormality)",
    "modifier": ""
  },
  "SPINAL_CANAL": {
    "name": "Spinal canal",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "61853006",
    "typeScheme": "SCT",
    "typeMeaning": "Spinal canal structure (body structure)",
    "modifier": ""
  },
  "PATHOLOGIC_CALCIFICATION": {
    "name": "Pathologic calcification",
    "categoryCode": "49755003",
    "categoryScheme": "SCT",
    "categoryMeaning": "Morphologically abnormal structure",
    "typeCode": "18115005",
    "typeScheme": "SCT",
    "typeMeaning": "Pathologic calcification, calcified structure (morphologic abnormality)",
    "modifier": ""
  },
  "PANCREATIC_DUCT": {
    "name": "Pancreatic duct",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "69930009",
    "typeScheme": "SCT",
    "typeMeaning": "Pancreatic duct structure (body structure)",
    "modifier": ""
  },
  "BILE_DUCT": {
    "name": "Bile duct",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "28273000",
    "typeScheme": "SCT",
    "typeMeaning": "Bile duct structure (body structure)",
    "modifier": ""
  },
  "RENAL_VEIN": {
    "name": "Renal vein",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "56400007",
    "typeScheme": "SCT",
    "typeMeaning": "Structure of renal vein (body structure)",
    "modifier": ""
  },
  "ARTERY": {
    "name": "Artery (unspecific)",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "51114001",
    "typeScheme": "SCT",
    "typeMeaning": "Arterial structure (body structure)",
    "modifier": ""
  },
  "VEIN": {
    "name": "Vein (unspecific)",
    "categoryCode": "123037004",
    "categoryScheme": "SCT",
    "categoryMeaning": "Body structure",
    "typeCode": "29092000",
    "typeScheme": "SCT",
    "typeMeaning": "Venous structure",
    "modifier": ""
  }
}
);

function normalizeSegKey(raw: string): string {
  return String(raw || "")
    .trim()
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

function normalizeNameKey(raw: string): string {
  return String(raw || "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

const SEGDB_BY_NAME: ReadonlyMap<string, string> = (() => {
  const map = new Map<string, string>();
  for (const [id, entry] of Object.entries(SEGDB_BY_ID)) {
    const nameKey = normalizeNameKey(entry.name);
    if (nameKey && !map.has(nameKey)) map.set(nameKey, id);
    const idAsName = normalizeNameKey(id.replace(/_/g, " "));
    if (idAsName && !map.has(idAsName)) map.set(idAsName, id);
  }
  return map;
})();

/** Resolve a SegDB id from segment label or SegDB id string. */
export function resolveSegdbId(labelOrId: string | null | undefined): string | null {
  const raw = String(labelOrId || "").trim();
  if (!raw) return null;
  const asId = normalizeSegKey(raw);
  if (asId && SEGDB_BY_ID[asId]) return asId;
  const byName = SEGDB_BY_NAME.get(normalizeNameKey(raw));
  return byName || null;
}

function coded(
  scheme: string,
  value: string,
  meaning: string,
): SegdbCoded | null {
  const v = String(value || "").trim();
  if (!v) return null;
  return {
    scheme: String(scheme || "SCT"),
    value: v,
    meaning: String(meaning || "").trim(),
  };
}

/** Build catalog-style terminology from a SegDB entry. */
export function terminologyFromSegdbEntry(entry: SegdbEntry): SegdbTerminology {
  return {
    category: coded(
      entry.categoryScheme,
      entry.categoryCode,
      entry.categoryMeaning,
    ),
    type: coded(entry.typeScheme, entry.typeCode, entry.typeMeaning),
    typeModifier: null,
    region: null,
  };
}

/**
 * Look up SegDB terminology for a segment label / id.
 * Returns null when no match.
 */
export function lookupSegdbTerminology(
  labelOrId: string | null | undefined,
): SegdbTerminology | null {
  const id = resolveSegdbId(labelOrId);
  if (!id) return null;
  const entry = SEGDB_BY_ID[id];
  if (!entry) return null;
  return terminologyFromSegdbEntry(entry);
}

/**
 * Fill missing type/category codes from SegDB; never overrides existing codes.
 */
export function enrichTerminologyFromSegdb<T extends {
  category: SegdbCoded | null;
  type: SegdbCoded | null;
  typeModifier: SegdbCoded | null;
  region: SegdbCoded | null;
}>(
  label: string | null | undefined,
  terminology: T | null | undefined,
): T | undefined {
  const hasType = Boolean(terminology?.type?.value);
  const hasCategory = Boolean(terminology?.category?.value);
  if (hasType && hasCategory) return terminology || undefined;
  const fromDb = lookupSegdbTerminology(label);
  if (!fromDb) return terminology || undefined;
  return {
    category: hasCategory ? terminology!.category : fromDb.category,
    type: hasType ? terminology!.type : fromDb.type,
    typeModifier: terminology?.typeModifier ?? fromDb.typeModifier,
    region: terminology?.region ?? fromDb.region,
  } as T;
}
