/**
 * OMI FHIR algorithm registry browser — static Device catalog from
 * omi-fhir-registry.json (generated by SlicerHub export_omi_fhir.mjs).
 */
import {
  clearHubDialogNearAnchor,
  placeHubDialogNearAnchor,
} from '@slicer-hub/client';
import registry from './omi-fhir-registry.json';

const MODAL_ANCHORED = 'wl-modal-backdrop-anchored';

type OmiAlgo = {
  id: string;
  source: string;
  label: string;
  modelName: string;
  version: string;
  modalities: string[];
  aiServiceType: string;
  maturityLevel: string;
  description: string;
  websiteUrl: string;
  githubUrl: string;
  inputProfile: string;
  outputProfile: string;
  device: Record<string, unknown>;
};

type OmiRegistry = {
  generated: string;
  omiDeviceProfile: string;
  algorithmCount: number;
  algorithms: OmiAlgo[];
};

const catalog = registry as OmiRegistry;

let selectedId: string | null = null;
let filterSource = 'all';
let filterModality = 'all';
let filterText = '';
let wired = false;

function escapeHtml(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function uniqueModalities(): string[] {
  const set = new Set<string>();
  for (const a of catalog.algorithms) {
    for (const m of a.modalities || []) set.add(m);
  }
  return [...set].sort();
}

function filteredAlgorithms(): OmiAlgo[] {
  const q = filterText.trim().toLowerCase();
  return catalog.algorithms.filter((a) => {
    if (filterSource !== 'all' && a.source !== filterSource) return false;
    if (
      filterModality !== 'all' &&
      !(a.modalities || []).includes(filterModality)
    ) {
      return false;
    }
    if (!q) return true;
    const hay = [
      a.label,
      a.modelName,
      a.id,
      a.description,
      a.aiServiceType,
      ...(a.modalities || []),
    ]
      .join(' ')
      .toLowerCase();
    return hay.includes(q);
  });
}

function selectedAlgo(): OmiAlgo | null {
  const id = selectedId;
  if (!id) return null;
  return catalog.algorithms.find((a) => a.id === id) || null;
}

function renderListHtml(algos: OmiAlgo[]): string {
  if (!algos.length) {
    return `<p class="wl-omi-empty">No algorithms match the current filters.</p>`;
  }
  return (
    `<ul class="wl-omi-list" role="listbox">` +
    algos
      .map((a) => {
        const active = a.id === selectedId ? ' wl-omi-list-item-active' : '';
        const mods = escapeHtml((a.modalities || []).join(', '));
        return (
          `<li class="wl-omi-list-item${active}" role="option" data-omi-id="${escapeHtml(a.id)}" tabindex="0">` +
          `<span class="wl-omi-list-label">${escapeHtml(a.label)}</span>` +
          `<span class="wl-omi-list-meta">` +
          `<span class="wl-omi-pill">${escapeHtml(a.source)}</span>` +
          `<span class="wl-omi-pill">${mods || '—'}</span>` +
          `<span class="wl-omi-pill">${escapeHtml(a.aiServiceType)}</span>` +
          `</span>` +
          `</li>`
        );
      })
      .join('') +
    `</ul>`
  );
}

function renderDetailHtml(algo: OmiAlgo | null): string {
  if (!algo) {
    return `<p class="wl-omi-empty">Select an algorithm to view its OMI FHIR Device resource.</p>`;
  }
  const json = JSON.stringify(algo.device, null, 2);
  const links = [
    algo.websiteUrl
      ? `<a href="${escapeHtml(algo.websiteUrl)}" target="_blank" rel="noopener noreferrer">Website</a>`
      : '',
    algo.githubUrl
      ? `<a href="${escapeHtml(algo.githubUrl)}" target="_blank" rel="noopener noreferrer">GitHub</a>`
      : '',
  ]
    .filter(Boolean)
    .join(' · ');

  return (
    `<div class="wl-omi-detail-head">` +
    `<h3 class="wl-omi-detail-title">${escapeHtml(algo.label)}</h3>` +
    `<p class="wl-omi-detail-sub">` +
    `${escapeHtml(algo.modelName)} · v${escapeHtml(algo.version)} · ` +
    `${escapeHtml(algo.maturityLevel)} · ${escapeHtml(algo.source)}` +
    `</p>` +
    (algo.description
      ? `<p class="wl-omi-detail-desc">${escapeHtml(algo.description)}</p>`
      : '') +
    (links ? `<p class="wl-omi-detail-links">${links}</p>` : '') +
    `<p class="wl-omi-detail-profiles">` +
    `<span>Input: <code>${escapeHtml(algo.inputProfile)}</code></span>` +
    `<span>Output: <code>${escapeHtml(algo.outputProfile)}</code></span>` +
    `</p>` +
    `<div class="wl-omi-detail-actions">` +
    `<button type="button" class="wl-omi-copy-btn" data-omi-copy>Copy Device JSON</button>` +
    `</div>` +
    `</div>` +
    `<pre class="wl-omi-json" tabindex="0">${escapeHtml(json)}</pre>`
  );
}

function renderBody(): void {
  const body = document.getElementById('omiFhirBody');
  if (!body) return;
  const algos = filteredAlgorithms();
  if (
    selectedId &&
    !algos.some((a) => a.id === selectedId) &&
    algos.length
  ) {
    selectedId = algos[0].id;
  } else if (!selectedId && algos.length) {
    selectedId = algos[0].id;
  } else if (!algos.length) {
    selectedId = null;
  }

  const mods = uniqueModalities();
  body.innerHTML =
    `<div class="wl-omi-layout">` +
    `<div class="wl-omi-sidebar">` +
    `<div class="wl-omi-filters">` +
    `<input type="search" class="wl-omi-search" data-omi-search placeholder="Filter algorithms…" value="${escapeHtml(filterText)}" />` +
    `<select class="wl-omi-select" data-omi-source aria-label="Source">` +
    `<option value="all"${filterSource === 'all' ? ' selected' : ''}>All sources</option>` +
    `<option value="product"${filterSource === 'product' ? ' selected' : ''}>Products</option>` +
    `<option value="mhub"${filterSource === 'mhub' ? ' selected' : ''}>MHub</option>` +
    `<option value="sam"${filterSource === 'sam' ? ' selected' : ''}>SAM</option>` +
    `</select>` +
    `<select class="wl-omi-select" data-omi-modality aria-label="Modality">` +
    `<option value="all"${filterModality === 'all' ? ' selected' : ''}>All modalities</option>` +
    mods
      .map(
        (m) =>
          `<option value="${escapeHtml(m)}"${filterModality === m ? ' selected' : ''}>${escapeHtml(m)}</option>`
      )
      .join('') +
    `</select>` +
    `</div>` +
    `<p class="wl-omi-count">${algos.length} / ${catalog.algorithmCount} algorithms</p>` +
    renderListHtml(algos) +
    `</div>` +
    `<div class="wl-omi-detail" data-omi-detail>` +
    renderDetailHtml(selectedAlgo()) +
    `</div>` +
    `</div>`;
}

async function copySelectedJson(): Promise<void> {
  const algo = selectedAlgo();
  if (!algo) return;
  const text = JSON.stringify(algo.device, null, 2);
  try {
    await navigator.clipboard.writeText(text);
  } catch {
    /* ignore */
  }
}

function onBodyClick(ev: Event): void {
  const t = ev.target as HTMLElement | null;
  if (!t) return;
  const copyBtn = t.closest('[data-omi-copy]');
  if (copyBtn) {
    void copySelectedJson();
    return;
  }
  const item = t.closest('[data-omi-id]') as HTMLElement | null;
  if (item?.dataset.omiId) {
    selectedId = item.dataset.omiId;
    renderBody();
  }
}

function onBodyChange(ev: Event): void {
  const t = ev.target as HTMLElement | null;
  if (!t) return;
  if (t.matches('[data-omi-source]')) {
    filterSource = (t as HTMLSelectElement).value;
    renderBody();
  } else if (t.matches('[data-omi-modality]')) {
    filterModality = (t as HTMLSelectElement).value;
    renderBody();
  }
}

function onBodyInput(ev: Event): void {
  const t = ev.target as HTMLElement | null;
  if (t?.matches('[data-omi-search]')) {
    filterText = (t as HTMLInputElement).value;
    renderBody();
    const search = document.querySelector(
      '[data-omi-search]'
    ) as HTMLInputElement | null;
    if (search) {
      search.focus();
      const len = search.value.length;
      search.setSelectionRange(len, len);
    }
  }
}

export function openOmiFhirDialog(anchor?: HTMLElement | null): void {
  const modal = document.getElementById('omiFhirModal');
  const titleEl = document.getElementById('omiFhirTitle');
  const dialog = modal?.querySelector('.wl-omi-modal') as HTMLElement | null;
  if (!modal || !titleEl) return;

  titleEl.textContent = `OMI Registry · ${catalog.algorithmCount} algorithms`;
  if (!selectedId && catalog.algorithms.length) {
    selectedId = catalog.algorithms[0].id;
  }
  renderBody();
  modal.hidden = false;
  placeHubDialogNearAnchor({
    overlay: modal,
    dialog,
    anchor: anchor ?? null,
    anchoredClass: MODAL_ANCHORED,
    align: 'end',
  });
}

export function closeOmiFhirDialog(): void {
  const modal = document.getElementById('omiFhirModal');
  if (!modal) return;
  const dialog = modal.querySelector('.wl-omi-modal') as HTMLElement | null;
  modal.hidden = true;
  clearHubDialogNearAnchor(modal, dialog, MODAL_ANCHORED);
}

export function wireOmiFhirDialog(): void {
  if (wired) return;
  wired = true;

  const modal = document.getElementById('omiFhirModal');
  const body = document.getElementById('omiFhirBody');
  const btn = document.getElementById('openOmiFhirBtn');

  body?.addEventListener('click', onBodyClick);
  body?.addEventListener('change', onBodyChange);
  body?.addEventListener('input', onBodyInput);

  modal?.querySelectorAll('[data-close-omi-fhir]').forEach((el) => {
    el.addEventListener('click', () => closeOmiFhirDialog());
  });
  modal?.addEventListener('click', (ev) => {
    if (ev.target === modal) closeOmiFhirDialog();
  });

  btn?.addEventListener('click', () => {
    openOmiFhirDialog(btn instanceof HTMLElement ? btn : null);
  });
}
